CREATE TABLE Chat (
    id TEXT PRIMARY KEY NOT NULL,
    title VARCHAR(255) NOT NULL,
    visibility TEXT NOT NULL DEFAULT 'public',
    folderId TEXT NOT NULL DEFAULT 'general',
    isBookmarked BOOLEAN NOT NULL DEFAULT false,
    isArchived BOOLEAN NOT NULL DEFAULT false,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Message (
    id TEXT PRIMARY KEY NOT NULL,
    chatId TEXT NOT NULL,
    content TEXT NOT NULL,
    role TEXT NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (chatId) REFERENCES Chat(id) ON DELETE CASCADE
);

CREATE TABLE Folder (
    id TEXT PRIMARY KEY NOT NULL,
    name TEXT NOT NULL UNIQUE,
    visibility TEXT NOT NULL DEFAULT 'public',
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
