import type { Metadata } from 'next';
import { Source_Sans_3, JetBrains_Mono } from 'next/font/google';
import './globals.css';
import { MainLayout } from '@/components/layout/main-layout';
import { cookies } from 'next/headers';

const fontSans = Source_Sans_3({
  variable: '--font-sans',
  subsets: ['latin'],
});

const fontMono = JetBrains_Mono({
  variable: '--font-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookie = await cookies();
  const sidebarCollapsed = cookie.get('sidebarCollapsed')?.value === 'true';

  return (
    <html lang="en" className="dark" suppressHydrationWarning>
      <body
        className={`${fontSans.variable} ${fontMono.variable} antialiased`}
        suppressHydrationWarning
      >
        <MainLayout sidebarFromCookie={sidebarCollapsed}>{children}</MainLayout>
      </body>
    </html>
  );
}
